// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiu5nw-LEyUptQgiVj-jfGT2EN0OvSs7M',
    appId: '1:715048636910:web:f0e6cb6bffc9a40c8e3eff',
    messagingSenderId: '715048636910',
    projectId: 'alash-hackathon',
    authDomain: 'alash-hackathon.firebaseapp.com',
    storageBucket: 'alash-hackathon.appspot.com',
    measurementId: 'G-X1CDGB4QBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv98aD4C8JGzCaSiD4rUXw9wP5hopVLaE',
    appId: '1:715048636910:android:217fc29530920c678e3eff',
    messagingSenderId: '715048636910',
    projectId: 'alash-hackathon',
    storageBucket: 'alash-hackathon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFXgFzqb1OrInohYWw5HdMqAeIvT8lzBc',
    appId: '1:715048636910:ios:9d0dd89c0a2f1e978e3eff',
    messagingSenderId: '715048636910',
    projectId: 'alash-hackathon',
    storageBucket: 'alash-hackathon.appspot.com',
    iosClientId: '715048636910-0oqcklld6um7hslsc54obo8d2vr9r0gd.apps.googleusercontent.com',
    iosBundleId: 'com.example.triton',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFXgFzqb1OrInohYWw5HdMqAeIvT8lzBc',
    appId: '1:715048636910:ios:9d0dd89c0a2f1e978e3eff',
    messagingSenderId: '715048636910',
    projectId: 'alash-hackathon',
    storageBucket: 'alash-hackathon.appspot.com',
    iosClientId: '715048636910-0oqcklld6um7hslsc54obo8d2vr9r0gd.apps.googleusercontent.com',
    iosBundleId: 'com.example.triton',
  );
}
